In [2]:
import pandas as pd

In [3]:
customer_df = pd.read_csv('../data/raw/customers.csv')
geolocation_df = pd.read_csv('../data/raw/geolocation.csv')
order_items_df = pd.read_csv('../data/raw/order_items.csv')
order_payments_df = pd.read_csv('../data/raw/order_payments.csv') 
order_reviews_df = pd.read_csv('../data/raw/order_reviews.csv')
orders_df = pd.read_csv('../data/raw/orders.csv')
products_df = pd.read_csv('../data/raw/products.csv')
sellers_df = pd.read_csv('../data/raw/sellers.csv')
product_category_name_translation_df = pd.read_csv('../data/raw/product_category_name_translation.csv')

In [5]:
orders_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [1]:
orders_df.info()

NameError: name 'orders_df' is not defined

In [8]:
sellerszip = list(sellers_df["seller_zip_code_prefix"])
sellerszip

[13023,
 13844,
 20031,
 4195,
 12914,
 20920,
 55325,
 16304,
 1529,
 80310,
 75110,
 13530,
 1222,
 5372,
 88705,
 42738,
 88780,
 70740,
 45810,
 5138,
 11440,
 14910,
 4156,
 13320,
 98910,
 30494,
 86707,
 9850,
 4857,
 18500,
 80210,
 2261,
 88495,
 3562,
 37650,
 17602,
 7241,
 83050,
 3445,
 4133,
 72233,
 70645,
 88730,
 88075,
 13416,
 90850,
 37584,
 31950,
 31555,
 9251,
 4705,
 6144,
 13270,
 89214,
 11446,
 28990,
 88390,
 25730,
 95500,
 84010,
 6544,
 9121,
 13568,
 6056,
 14940,
 5741,
 83010,
 3702,
 6429,
 6192,
 95076,
 3569,
 89207,
 38440,
 32180,
 89258,
 14940,
 9715,
 88501,
 95711,
 15805,
 9400,
 4726,
 14882,
 19830,
 6713,
 89160,
 4275,
 18040,
 21235,
 14850,
 22420,
 1125,
 24813,
 5786,
 15137,
 9190,
 16200,
 3569,
 31730,
 20785,
 20060,
 14940,
 12401,
 1425,
 19803,
 13820,
 14801,
 27963,
 13320,
 13504,
 86039,
 5101,
 14010,
 21210,
 37410,
 4248,
 15190,
 14940,
 3514,
 71070,
 6465,
 1044,
 88870,
 70384,
 2310,
 2016,
 78095,
 13575,
 1040,
 3322,
 20261,
 85830,
 23550,
 11085,
 3417,
 76500,
 81210,
 8260,
 95995,
 4674,
 14020,
 36525,
 95072,
 55004,
 80045,
 14401,
 81030,
 40243,
 9951,
 8573,
 18682,
 7091,
 6341,
 76400,
 88301,
 3280,
 1545,
 1026,
 80620,
 87900,
 3186,
 19400,
 2839,
 87014,
 1207,
 1411,
 30190,
 8502,
 1541,
 13481,
 11040,
 6436,
 2310,
 35530,
 14080,
 24355,
 17700,
 6380,
 6016,
 24451,
 78820,
 88330,
 4009,
 89120,
 14075,
 5424,
 99730,
 60440,
 7242,
 7051,
 8517,
 16800,
 89228,
 30421,
 17056,
 12308,
 13304,
 85301,
 3554,
 89560,
 88058,
 6853,
 58280,
 8490,
 35430,
 87360,
 17280,
 6653,
 74563,
 4821,
 21820,
 1026,
 3308,
 95070,
 9640,
 58400,
 93608,
 27525,
 89251,
 2215,
 5524,
 22790,
 8041,
 5715,
 88032,
 18055,
 2112,
 14075,
 18048,
 9336,
 17030,
 17052,
 30620,
 13327,
 74343,
 35300,
 15350,
 21240,
 14407,
 16500,
 2518,
 14050,
 88730,
 36502,
 9751,
 3407,
 14940,
 87035,
 15062,
 13064,
 21020,
 13660,
 95660,
 9080,
 89031,
 9110,
 9230,
 3951,
 3172,
 3334,
 89070,
 8773,
 11013,
 6286,
 15155,
 35530,
 74045,
 18500,
 18048,
 1126,
 13478,
 1303,
 2739,
 20921,
 86170,
 14940,
 86808,
 15046,
 22230,
 87035,
 4102,
 7052,
 16301,
 24020,
 89204,
 83408,
 11450,
 26562,
 86010,
 2051,
 88056,
 30550,
 2820,
 85802,
 83830,
 4508,
 6775,
 1550,
 22783,
 81070,
 4716,
 12233,
 7084,
 3384,
 85903,
 82510,
 15081,
 8411,
 17047,
 11045,
 85960,
 80010,
 8710,
 91130,
 12238,
 6236,
 13203,
 83800,
 3551,
 8655,
 33200,
 80040,
 20735,
 89031,
 1417,
 98780,
 15015,
 14600,
 5125,
 81050,
 13830,
 1212,
 97502,
 80215,
 6703,
 13480,
 37400,
 14940,
 4811,
 75640,
 3306,
 95034,
 30640,
 89701,
 2880,
 3688,
 74043,
 37540,
 81925,
 6246,
 80510,
 80240,
 14780,
 13330,
 26525,
 9380,
 17580,
 44895,
 13840,
 4557,
 4311,
 11702,
 14406,
 22783,
 89128,
 2036,
 6038,
 88351,
 88804,
 5729,
 6519,
 6016,
 89222,
 2252,
 7179,
 31050,
 13480,
 15805,
 89052,
 31255,
 15704,
 20270,
 86060,
 12944,
 69900,
 86046,
 27321,
 5632,
 3161,
 4782,
 14403,
 87013,
 9405,
 2310,
 4363,
 1539,
 13560,
 2238,
 15055,
 82220,
 17520,
 3060,
 9443,
 14096,
 48602,
 91740,
 86047,
 85807,
 12020,
 85802,
 1320,
 12250,
 81250,
 29138,
 7145,
 88107,
 25850,
 13730,
 18130,
 37900,
 14940,
 85603,
 3821,
 36512,
 76400,
 87083,
 74473,
 21931,
 14055,
 88210,
 13105,
 26255,
 3343,
 17512,
 88820,
 3543,
 95910,
 3694,
 3029,
 37540,
 13042,
 1201,
 9230,
 88359,
 98920,
 4364,
 3416,
 9350,
 1214,
 2880,
 9220,
 18110,
 35530,
 93700,
 3659,
 1123,
 15910,
 3103,
 14078,
 15601,
 89041,
 17500,
 84010,
 7093,
 31560,
 13920,
 86800,
 7062,
 88351,
 8550,
 3471,
 87047,
 82040,
 15025,
 35500,
 13450,
 92025,
 13310,
 89217,
 13375,
 9628,
 6539,
 81350,
 86040,
 14405,
 35700,
 37165,
 85904,
 8780,
 13219,
 17509,
 60741,
 3311,
 13490,
 38410,
 75123,
 14092,
 15085,
 4578,
 91310,
 20756,
 1233,
 8223,
 4782,
 83402,
 9920,
 13419,
 20021,
 18072,
 13456,
 13920,
 86702,
 27277,
 13660,
 89030,
 6787,
 22790,
 16072,
 81830,
 74210,
 16200,
 18070,
 37580,
 13073,
 89248,
 38650,
 13150,
 14092,
 15800,
 1215,
 24451,
 4386,
 5547,
 21070,
 37706,
 24725,
 13160,
 11015,
 4209,
 30575,
 6513,
 20520,
 58030,
 17300,
 89245,
 1220,
 90230,
 83075,
 31570,
 36500,
 93310,
 84035,
 80330,
 89218,
 88056,
 15155,
 13170,
 83070,
 9350,
 85980,
 2118,
 12242,
 29313,
 14150,
 5108,
 86604,
 4360,
 23062,
 3029,
 4054,
 36415,
 15046,
 5537,
 12943,
 6852,
 83091,
 18035,
 18550,
 13405,
 3275,
 14400,
 88495,
 90010,
 17604,
 3612,
 5268,
 13660,
 3059,
 7600,
 1547,
 13041,
 16480,
 95360,
 17700,
 9862,
 37706,
 28495,
 35500,
 1021,
 17605,
 80610,
 18053,
 88715,
 86707,
 26210,
 8250,
 29101,
 14801,
 9182,
 89210,
 13085,
 21070,
 7194,
 36052,
 23080,
 38230,
 14960,
 18185,
 15840,
 87050,
 4815,
 29142,
 36320,
 88020,
 13560,
 11065,
 8598,
 62170,
 83409,
 13504,
 14940,
 95705,
 4041,
 12080,
 81210,
 87050,
 86026,
 1244,
 39400,
 82810,
 4613,
 9694,
 11701,
 7152,
 92310,
 82510,
 36570,
 13090,
 5201,
 3126,
 21041,
 82130,
 76804,
 40130,
 13720,
 32260,
 85501,
 36301,
 14091,
 19042,
 8743,
 26600,
 13312,
 13930,
 15052,
 9541,
 1420,
 1239,
 13418,
 13820,
 4001,
 17051,
 15081,
 9550,
 89256,
 2523,
 5462,
 83411,
 89069,
 36010,
 4154,
 28660,
 58385,
 14940,
 82800,
 4133,
 2851,
 89240,
 7052,
 29104,
 19010,
 32672,
 1303,
 4676,
 3910,
 81200,
 9411,
 81070,
 84430,
 83280,
 91520,
 5615,
 64033,
 4164,
 91360,
 14406,
 89900,
 18550,
 12941,
 12230,
 18132,
 86820,
 8020,
 14802,
 7135,
 17600,
 2562,
 84920,
 20751,
 70610,
 9190,
 85851,
 12080,
 9780,
 13483,
 13180,
 2215,
 8583,
 28633,
 21862,
 4438,
 3521,
 30120,
 37975,
 3654,
 36050,
 88085,
 5171,
 16200,
 35540,
 34710,
 19865,
 9810,
 31510,
 2515,
 15500,
 19025,
 13825,
 8752,
 88901,
 83324,
 2117,
 9540,
 4361,
 3306,
 86047,
 4213,
 14092,
 14026,
 16200,
 1254,
 74435,
 1026,
 26020,
 7140,
 90560,
 3307,
 2804,
 13480,
 22790,
 85948,
 99500,
 38680,
 13520,
 88504,
 4122,
 9320,
 1223,
 13660,
 6365,
 85640,
 35500,
 30180,
 83010,
 1026,
 35680,
 11443,
 3065,
 88063,
 3533,
 91901,
 13800,
 89224,
 89520,
 71906,
 37410,
 5849,
 60346,
 1403,
 2727,
 12215,
 8710,
 2565,
 4256,
 13088,
 13185,
 4160,
 30310,
 87025,
 20771,
 12940,
 88210,
 85900,
 17511,
 82940,
 35162,
 95059,
 88790,
 13920,
 2407,
 13041,
 12942,
 36071,
 1310,
 36213,
 5353,
 2532,
 9560,
 13603,
 37142,
 5138,
 7071,
 9111,
 18040,
 13085,
 17350,
 13473,
 88353,
 88350,
 9510,
 38412,
 14750,
 30120,
 14400,
 4131,
 22451,
 4317,
 1001,
 5705,
 81650,
 7160,
 18085,
 81020,
 79090,
 1226,
 3303,
 3567,
 9270,
 17400,
 19470,
 91510,
 14940,
 3613,
 31255,
 14940,
 74340,
 2124,
 14910,
 9726,
 85904,
 81730,
 89211,
 5174,
 45816,
 13481,
 61800,
 13930,
 4087,
 23095,
 73801,
 7023,
 3167,
 4833,
 24346,
 37564,
 81825,
 11680,
 85988,
 13566,
 37540,
 15813,
 11013,
 20751,
 6768,
 3550,
 35570,
 1139,
 11075,
 95012,
 27930,
 42738,
 31230,
 13506,
 95900,
 85804,
 14020,
 95800,
 79107,
 15041,
 88370,
 30130,
 9633,
 6717,
 2220,
 4456,
 11070,
 13481,
 6513,
 81050,
 12701,
 2372,
 14940,
 9920,
 5041,
 87050,
 97050,
 71200,
 18047,
 15085,
 15130,
 6033,
 36886,
 1311,
 2510,
 92420,
 22745,
 9810,
 15076,
 27274,
 7170,
 4144,
 5319,
 5315,
 4827,
 9230,
 95240,
 1230,
 59775,
 25750,
 1224,
 13082,
 2751,
 81540,
 13660,
 37004,
 31130,
 91150,
 72125,
 14050,
 18608,
 81320,
 8220,
 29260,
 13030,
 3644,
 38010,
 19027,
 1031,
 3282,
 35170,
 3390,
 94930,
 5311,
 14940,
 3333,
 9320,
 24754,
 9820,
 15014,
 14092,
 19820,
 4088,
 17400,
 7043,
 38414,
 13481,
 4160,
 4693,
 3060,
 13632,
 2116,
 8280,
 18015,
 18015,
 4567,
 31844,
 14020,
 13030,
 7402,
 ...]

In [12]:
no = 0
yes = 0
for i in sellerszip:
    seller_location = geolocation_df[ geolocation_df["geolocation_zip_code_prefix"] == i]
    if seller_location.empty:
        no+=1 
    else:
        yes+=1

In [13]:
print(f"no: {no}::::: yes: {yes}")

no: 7::::: yes: 3088

In [36]:
len(sellers_df)

3095

In [38]:
sellers_map_data = pd.merge(
    sellers_df,
    geolocation_df,
    left_on="seller_zip_code_prefix",
    right_on="geolocation_zip_code_prefix",
    how="left" # Keep all sellers, even if they don't have a map match
)

In [39]:
len(sellers_map_data)

435094

In [44]:
order_items_df.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [16]:
geo_clean = geolocation_df.groupby('geolocation_zip_code_prefix').first().reset_index()

# Optional: If you only want specific columns to keep the merge clean
geo_clean = geo_clean[[
    'geolocation_zip_code_prefix', 
    'geolocation_lat', 
    'geolocation_lng', 
    'geolocation_city', 
    'geolocation_state'
]]

In [17]:
geo_clean

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1001,-23.549292,-46.633559,sao paulo,SP
1,1002,-23.548318,-46.635421,sao paulo,SP
2,1003,-23.549032,-46.635313,sao paulo,SP
3,1004,-23.550116,-46.635122,sao paulo,SP
4,1005,-23.549819,-46.635606,sao paulo,SP
...,...,...,...,...,...
19010,99960,-27.953797,-52.029641,charrua,RS
19011,99965,-28.173892,-52.038447,agua santa,RS
19012,99970,-28.345143,-51.876926,ciriaco,RS
19013,99980,-28.389218,-51.846012,david canabarro,RS
19014,99990,-28.329718,-51.769615,muliterno,RS

In [18]:
len(geolocation_df)

1000163